### ISSUE TITLE
Change license to ISC

### ISSUE THREAD

**Issue by j8r** [crystal-community/hardware#13]
I propose to change the license to the OpenBSD variant of the [ISC license](https://en.wikipedia.org/wiki/ISC_license) (because *and/or* is pointless), and changing the copyright to `(c) 2017-2018 Bar Hofesh, Julien Reichardt and Crystal Community contributors`

WDYT @bararchy @veelenga ?

**Comment by bararchy** [comment]
@j8r Not against.

**Comment by veelenga** [comment]
@j8r @bararchy 👍
