### ISSUE TITLE
Int32 not big enough for big machines

### ISSUE THREAD

**Issue by Jaciones** [crystal-community/hardware#16]
Ran into some issues trying to run specs on my machine.

crystal spec

Unhandled exception: Invalid Int32: 10938615520 (ArgumentError)
  from /usr/share/crystal/src/string.cr:411:83 in 'to_i32'
  from /usr/share/crystal/src/string.cr:322:5 in 'to_i'
  from src/hardware/cpu.cr:25:73 in 'update_stat'
  from src/hardware/cpu.cr:20:13 in 'initialize'
  from src/hardware/cpu.cr:19:3 in 'new'
  from spec/cpu_spec.cr:4:9 in '->'
  from /usr/share/crystal/src/spec/context.cr:255:3 in 'describe'
  from /usr/share/crystal/src/spec/methods.cr:18:5 in 'describe'
  from spec/memory_spec.cr:1:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???

**Comment by j8r** [comment]
I should be fixed by #15

**Comment by j8r** [comment]
Thanks to have reported this. Be free to reopen if not fixed.
